### ISSUE TITLE
i keep getting an access denied error

### ISSUE THREAD

**Issue by Moddieyt** [MCMi460/3DS-RPC#14]
Traceback (most recent call last):
  File "app.py", line 239, in <module>
  File "client.py", line 51, in __init__
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\moddie\\Documents\\3DS-RPC\\private.txt'

**Comment by Moddieyt** [comment]
nevermind, i fixed it by moving the 3ds-rpc directory.
