### ISSUE TITLE
Invalid Friend Code (#6 all again)

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [MCMi460/3DS-RPC#9]
Decided to open an issue as I couldn’t re-open #6 (And didn’t knew if I should have continued there)
```python
Traceback (most recent call last):
  File "/home/pm/Documents/3DS-RPC/client/client.py", line 218, in <module>
    main()
  File "/home/pm/Documents/3DS-RPC/client/client.py", line 205, in main
    raise e
  File "/home/pm/Documents/3DS-RPC/client/client.py", line 201, in main
    client = Client(friendCode, config)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pm/Documents/3DS-RPC/client/client.py", line 40, in __init__
    friendCode = str(convertPrincipalIdtoFriendCode(convertFriendCodeToPrincipalId(friendCode))).zfill(12) # Friend Code check
                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pm/Documents/3DS-RPC/client/../api/love.py", line 24, in convertFriendCodeToPrincipalId
    if not checkPrincipalIdValidity(checksumByte, principalId): raise FriendCodeValidityError('an invalid friend code was passed')
                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api.love.FriendCodeValidityError: an invalid friend code was passed
```
`4425-1804-5982` (Tried with `-` as well)

**Comment by MCMi460** [comment]
Thank you for telling me of this lol
Another leading zero error!

**Comment by MCMi460** [comment]
Since this breaks the current build of the server, I'm going to have to manually update the server, which means merging with the main branch. Give me ~10 minutes and the server will be back up again. You'll need to re-clone the main branch, though.
Thank you again for notifying me! Zeros will be the death of me, I swear.

**Comment by MCMi460** [comment]
Okay, it should be working now.
Please let me know if anything goes awry in the future. Thank you again!
